sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  firefox: "46.0"
  hosts:
      - magento2.travis
language: php
php:
  - 7.1
#before_install: ./before_install.sh
#install: composer install --no-interaction --prefer-dist
before_script:
  - mkdir pull_disk
  - git clone -b master --depth 1 https://github.com/Magestore/FulfilSuccess-M2.git ./pull_disk
script:
  - ls -lah pull_disk
